### ISSUE TITLE
include python-swiftclient in setup install_requires

### ISSUE THREAD

**Issue by WhiteAu** [FredHutch/sci-pkg#5]
File "C:/Users/whiteau/Documents/GitHub/nlp-airflow-dags/active/utilities/scratch.py", line 4, in <module>
    MYSTOR = swift('fh-nlp-deid-swift')
  File "C:\Users\whiteau\Documents\GitHub\nlp-airflow-dags\venv\lib\site-packages\sci\store.py", line 48, in __init__
    import swiftclient, json
ModuleNotFoundError: No module named 'swiftclient'

Was able to fix locally by installing package python-swiftclient

**Comment by dtenenba** [comment]
I think this is closed by ec41786178040345210bf8197abd8c9b1cfe627d , please check.

**Comment by dtenenba** [comment]
BTW, in future, I suggest installing the pkg by cloning the github repo (doing git pull if you already have cloned it) and running `python setup.py install`. I suggest this because we should be judicious with version bumps. But using the above install method we will be able to tell if issues have been fixed, even without version bumps.

**Comment by WhiteAu** [comment]
That's fair. I'll make a note of best install practice for the docker script.
