### ISSUE TITLE
Installation fails if PostgreSQL is not installed on workstation

### ISSUE THREAD

**Issue by bconn-proteinms** [FredHutch/sci-pkg#8]
I am looking to use the non-DB functions of sci package, but I cannot install it unless PostgreSQL in installed on my workstation. 

```
$ pip install sci
Collecting sci
  Downloading https://files.pythonhosted.org/packages/ba/7d/30847bd57f69defd6cd5a52372abfbbe5cd6a100d53e5556a8a8a42eb129/sci-0.1.7.tar.gz
Requirement already satisfied: requests in ~/.virtualenvs/VENV-NAME/lib/python3.6/site-packages (from sci)
Collecting python-hostlist (from sci)
  Downloading https://files.pythonhosted.org/packages/3d/0f/1846a7a0bdd5d890b6c07f34be89d1571a6addbe59efe59b7b0777e44924/python-hostlist-1.18.tar.gz
Collecting psycopg2 (from sci)
  Downloading https://files.pythonhosted.org/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 2.6MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    /usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
```

This occurred Mac running 10.13.6 with Python 3.6 installed via homebrew.

**Comment by dtenenba** [comment]
I wonder if we should split off the database functions into a separate package so that users who only need the storage components will not have to worry about having the right dependencies.

(For the record, if you want to know how to install pg_config on a mac so that you *can* install psycopg2, go here: https://stackoverflow.com/questions/21079820/how-to-find-pg-config-path )

One other thing for the dev team to consider; there is a binary package (psycopg2-binary) in PyPi at https://pypi.org/project/psycopg2-binary/ . We could make `sci` depend on this instead of psycopg2. While this is not necessarily recommended, we need to balance that against users who will give up in frustration even if we document carefully how to install the prerequisites for sci (which we should do, but as Brian points out, many people are not going to want to install postgres libraries just so they can use object storage functions in sci). 

I tested psycopg2-binary on Mac and Linux and it works fine, and does not require that any postgresql component be installed on the machine. I am going to make a PR that changes things to depend on psycopg2-binary instead of psycopg2 (regardless of whether the source or binary package is installed, you use the package in the same way, with `import psycopg2`). 
If the PR is accepted and merged, it should resolve this issue.
